name: Page tests
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: jitterbit/get-changed-files@v1
      with:
        format: 'json'
    - uses: actions/setup-node@v2
      with:
        node-version: '16.x'
    - name: Page Tests
      run: |
        npm ci
        npm run test:headless
      env:
        CI: true
        FILES: steps.files.outputs.added_modified

