name: Tests
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v3
      with:
        node-version: '16.x'
        cache: 'npm'
    - name: install
      run: |
        npm ci
      env:
        PUPPETEER_SKIP_DOWNLOAD: 'true'
    - name: Build
      run: |
        npm run build
      env:
        CI_MODE: travis
        SIMKL_API_ID: ${{ secrets.SIMKL_API_ID }}
        SIMKL_API_SECRET: ${{ secrets.SIMKL_API_SECRET }}
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v3
      with:
        node-version: '16.x'
        cache: 'npm'
    - name: install
      run: |
        npm ci
      env:
        PUPPETEER_SKIP_DOWNLOAD: 'true'
    - name: Lint
      run: |
        npm run lint:ci
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v3
      with:
        node-version: '16.x'
        cache: 'npm'
    - name: install
      run: |
        npm ci
      env:
        PUPPETEER_SKIP_DOWNLOAD: 'true'
    - name: Build
      run: |
        npm run build:webextension:assets
        npm run build:webextension:content:build
      env:
        CI_MODE: travis
        SIMKL_API_ID: ${{ secrets.SIMKL_API_ID }}
        SIMKL_API_SECRET: ${{ secrets.SIMKL_API_SECRET }}
    - name: Tests
      run: |
        npm run test:ts:ci
      env:
        NO_API: true
